os: linux
dist: xenial

language: cpp

compiler:
- gcc

cache:
  directories:
  - /var/cache/apt/archives/*.deb
  - ./toolchain/local

before_install:
- sudo apt-get update
- sudo apt-get install -y libmpfr-dev libmpc-dev libgmp-dev
- sudo apt-get install -y e2fsprogs qemu-system-i386 qemu-utils
- sudo apt-get install -y mtools grub-pc-bin nasm python3

script:
- ./toolchain/build-it!.sh
- source ./toolbox/use-it!.sh
- source ./toolchain/use-it!.sh
- make all
